# 认证设置
publish_mode: editorial_workflow
site_url: https://skybook.pages.dev # 替换成你的博客线上地址
backend:
  repo: skybbk1001/skybook-hexo
  branch: main
  base_url: https://decap-server.vercel.app
  auth_endpoint: /api/auth
  name: git-gateway

# UI 配置
local_backend: true # 本地开发支持
locale: 'zh_Hant' # 后台 UI 语言

# 媒体文件
media_folder: "source/images/uploads"
public_folder: "/images/uploads"

# 内容集合 (定义文章结构)
collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts/好书推荐"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # 文章字段 (对应 Front-matter)
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "分类", name: "categories", widget: "list", required: false }
      - { label: "作者", name: "author", widget: "string", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
